### PR TITLE
Updates for ember 1.13+

### PR DESCRIPTION
**Pull request by tgreiser**
Updated the documentation and script to be compatible (no deprecation warnings) under 1.13. Not yet tested, but should work with Ember 2.0 also.

### CODE REVIEW

**Comment by listepo** [comment]
+1

**Comment by justin-lau** [comment]
Sorry guys, thanks a lot for the PR. I haven't had much time on Ember.js lately. This plugin was written when I needed intl-tel-input on one of my client's project that uses Ember.js. It was released right after the project is closed. I didn't have time to write tests for it, and I really need to conduct some testing to make sure everything still works with this PR, especially that there were quite a lot of moving parts on Ember and Ember CLI.

Tests related PR are welcomed, otherwise I will see if I can put them together next week.

**Comment by davidgoli** [comment]
@justin-lau I just pushed up a PR to backfill several tests. If you don't have time to review, I'd happily take over as owner.

**Comment by justin-lau** [comment]
@tgreiser, @davidgoli helped added some tests to the repo. and I have managed to updated the repo to run with ember and ember-cli 1.13.x. I found that in this PR there are something more than just updating it to 1.13. Would you mind submitted separated PRs so that I understand more easily what they're about?

**Comment by justin-lau** [comment]
I'm closing this PR for now. Feel free to bring this up again if you think there is necessity.

**Pull request closed without merging**
